# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

  
 [[main]]
  name = "About me"
  url = "#about"
  weight = 30
  

  
[[main]]
  name = "Posts"
  url = "#posts"
  weight = 40

#[[main]]
  #name = "Events"
  #url = ""
  #weight = 

#[[main]]
 #name = "Talks"
 #url = "#talks"
 #weight = 50 
 
 [[main]]
 name = "Projects & Talks"
 url = "#projects"
 weight = 55 
 
 [[main]]
  name = "Experience"
  url = "#experience"
  weight = 60
  
 [[main]]
  name = "Accomplishments"
  url = "#accomplishments"
  weight = 70 

#[[main]]
  #name = "Contact"
  #url = "#contact"
  #weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
